[
  {
    "code": "00",
    "msg": "操作成功",
    "commoditys": [
      {
        "fid": 17047,
        "name": "同享 九制话梅 35g",
        "price": 150,
        "beforeprice": 150,
        "photo": "resource/food/81427426376178.jpg",
        "status": 1,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 0,
        "ftid": 170
      },
      {
        "fid": 17043,
        "name": "纪州日式话梅160g",
        "price": 1700,
        "beforeprice": null,
        "photo": "resource/food/fang/421420288664764.JPEG",
        "status": 1,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 0,
        "ftid": 170
      },
      {
        "fid": 17039,
        "name": "富新园奶油梅",
        "price": 1000,
        "beforeprice": null,
        "photo": "resource/food/fang/261420282035976.JPEG",
        "status": 1,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 0,
        "ftid": 170
      },
      {
        "fid": 17035,
        "name": "富新园甜酸乌梅",
        "price": 1000,
        "beforeprice": null,
        "photo": "resource/food/fang/781420281594510.JPEG",
        "status": 1,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 0,
        "ftid": 170
      },
      {
        "fid": 17034,
        "name": "富新园话梅条",
        "price": 1000,
        "beforeprice": null,
        "photo": "resource/food/fang/941420281310351.JPEG",
        "status": 1,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 0,
        "ftid": 170
      },
      {
        "fid": 17030,
        "name": "盐津梅肉110g",
        "price": 600,
        "beforeprice": null,
        "photo": "resource/food/fang/991420279028097.JPEG",
        "status": 1,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 0,
        "ftid": 170
      },
      {
        "fid": 17026,
        "name": "真之味秘制话梅",
        "price": 700,
        "beforeprice": null,
        "photo": "resource/food/fang/91420278957732.JPEG",
        "status": 1,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 0,
        "ftid": 170
      },
      {
        "fid": 17022,
        "name": "荔园爽脆梅",
        "price": 400,
        "beforeprice": null,
        "photo": "resource/food/fang/391420278784840.JPEG",
        "status": 0,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 30,
        "ftid": 170
      },
      {
        "fid": 17018,
        "name": "西琪冰糖杨梅200克",
        "price": 750,
        "beforeprice": 800,
        "photo": "resource/food/fang/741419904822447.JPEG",
        "status": 0,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 30,
        "ftid": 170
      },
      {
        "fid": 17014,
        "name": "真之味薄荷话梅",
        "price": 700,
        "beforeprice": null,
        "photo": "resource/food/fang/431419841554465.JPEG",
        "status": 0,
        "smsg": "已售完",
        "sales": 0,
        "ishot": 0,
        "isnew": 0,
        "sellerid": 14,
        "sellername": "鸿程便利店",
        "stock": 30,
        "ftid": 170
      }
    ]
  }
]